# .gitlab_ci.yml (version 4 - -- add code complexity checks))

image: python:latest


variables:
    BUILD_TYPE: draft # you can change e.g. to release when the time comes

before_script:
    - python --version
    - pip install pytest
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo $REPO_NAME
    - echo $CI_COMMIT_BRANCH
    - echo $CI_PROJECT_DIR
    - pwd


stages: # List of stages for jobs, and their order of execution
    - unit_tests
    - quality
    - integration


# **************** UNIT TESTING stage ****************************

tests_add:
  stage: unit_tests
  script:
    - echo "Running unit tests for add... "
    - echo $CI_COMMIT_BRANCH
    - cd $CI_PROJECT_DIR/DEV/calculator/our_add
    - pytest
  only:
    - tomasploureiro   #this step only runs when the commit occurs in the 41-add branch


# **************** QUALITY stage ****************************

coding_style:
  stage: quality
  before_script:
    - pip install flake8
  script:
    - echo "Checking coding style... "
    - echo $CI_COMMIT_BRANCH
    - cd $CI_PROJECT_DIR/DEV/calculator
    - flake8 --max-line-length=120 calculator.py
  allow_failure: true #default is false;
  only:
    - tomasploureiro   #this step only runs when the commit occurs in the 41-add branch

code_complexity:
  stage: quality
  before_script:
    - pip install xenon
  script:
    - echo "Checking code complexity... "
    - echo $CI_COMMIT_BRANCH
    - xenon -b A -m A -a A --ignore='venv' . 
            # -b A : At least one block has a complexity rank higher than A (i.e. B, C, D, E or F)
            # -m A : At least one module has a complexity rank higher than A (i.e. B, C, D, E or F)
            # -a A : Average complexity has rank higher than A (i.e. B , C, D, E or F)
  allow_failure: true #default is false;
  only:
    - tomasploureiro   #this step only runs when the commit occurs in the 41-add branch

# **************** INTEGRATION stage ****************************

integration:
  stage: integration
  script:
    - echo "Running integration tests at calculator level... "
    - echo $CI_COMMIT_BRANCH
    - cd $CI_PROJECT_DIR/DEV/calculator/
    - pytest test_calculator.py
  only:
  #  - 41-add   #this step only runs when the commit occurs in the 41-add branch
    - tomasploureiro #this step only runs when the commit occurs in the main trunk

test_coverage:
  stage: integration
  before_script:
    - pip install pytest pytest-cov
  script:
  - echo "Assessing test coverage... "
  - echo $CI_COMMIT_BRANCH
  - cd $CI_PROJECT_DIR/DEV/calculator/
  - pytest --cov=. --cov-report=html --cov-report=term # report goes to terminal and htmlcov → open 'index.html' in a browser
  artifacts:
    paths:
      - $CI_PROJECT_DIR/DEV/calculator/htmlcov/ # Preserve the html coverage files as an artifact
    expire_in: 1 day  # (Optional) Specify how long to keep the artifact
    # (e.g., 1 week, 1 day, never).
  only:
  #  - 41-add   #this step only runs when the commit occurs in the 41-add branch
    - tomasploureiro #this step only runs when the commit occurs in the main trunk



